; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=s1c33 -O2 < %s | FileCheck %s

; Verify that large-immediate ALU operations use 3-operand ext form.

; and with 16-bit mask — uses ext+ext+and 3-operand form
define i32 @test_and_16bit(i32 %a) {
; CHECK-LABEL: test_and_16bit:
; CHECK:      ext 7
; CHECK-NEXT: ext 8191
; CHECK-NEXT: and %r10, %r12
; CHECK-NOT:  ld.w
entry:
  %r = and i32 %a, 65535
  ret i32 %r
}

; or with large constant: ext+ext+or 3-operand form
define i32 @test_or_large(i32 %a) {
; CHECK-LABEL: test_or_large:
; CHECK:      ext 7
; CHECK-NEXT: ext 7936
; CHECK-NEXT: or %r10, %r12
; CHECK-NOT:  ld.w
entry:
  %r = or i32 %a, 65280
  ret i32 %r
}

; xor with 0xFF: ext+xor 3-operand form (13-bit imm fits in 1 ext)
define i32 @test_xor_255(i32 %a) {
; CHECK-LABEL: test_xor_255:
; CHECK:      ext 255
; CHECK-NEXT: xor %r10, %r12
; CHECK-NOT:  ld.w
entry:
  %r = xor i32 %a, 255
  ret i32 %r
}

; sub with constant > 63: ext+sub 3-operand form
define i32 @test_sub_100(i32 %a) {
; CHECK-LABEL: test_sub_100:
; CHECK:      ext 100
; CHECK-NEXT: sub %r10, %r12
; CHECK-NOT:  add
entry:
  %r = sub i32 %a, 100
  ret i32 %r
}

; sub with constant in 0..63: direct sub_ri (no ext)
define i32 @test_sub_small(i32 %a) {
; CHECK-LABEL: test_sub_small:
; CHECK:      sub %r10, 10
; CHECK-NOT:  ext
entry:
  %r = sub i32 %a, 10
  ret i32 %r
}

; Decrement idiom: (add x, -1) → sub x, 1
define i32 @test_decrement(i32 %a) {
; CHECK-LABEL: test_decrement:
; CHECK:      sub %r10, 1
; CHECK-NOT:  ld.w
entry:
  %r = add i32 %a, -1
  ret i32 %r
}

; Decrement by 63: (add x, -63) → sub x, 63
define i32 @test_decrement_63(i32 %a) {
; CHECK-LABEL: test_decrement_63:
; CHECK:      sub %r10, 63
entry:
  %r = add i32 %a, -63
  ret i32 %r
}

; (add x, -100): should become ext+sub 3-operand form
define i32 @test_add_neg100(i32 %a) {
; CHECK-LABEL: test_add_neg100:
; CHECK:      ext 100
; CHECK-NEXT: sub %r10, %r12
; CHECK-NOT:  add %r
entry:
  %r = add i32 %a, -100
  ret i32 %r
}

; cmp with 1000 on the BR_CC path — CMP_ri32 pseudo emits ext+cmp %rd,sign6
; directly (2-op form), avoiding materialization into a scratch register.
define void @test_cmp_1000_br(i32 %x, ptr %p) {
; CHECK-LABEL: test_cmp_1000_br:
; CHECK:      ext 15
; CHECK-NEXT: cmp %r12, -24
; CHECK-NOT:  ld.w %r{{[0-9]+}}, -24
entry:
  %c = icmp eq i32 %x, 1000
  br i1 %c, label %a, label %b
a:
  store i32 11, ptr %p
  ret void
b:
  store i32 22, ptr %p
  ret void
}

; cmp with -100 via icmp eq — direct 2-op ext form.
; -100 = 0x7FF9C in 19-bit two's complement: ext=8190, sign6=28.
define void @test_cmp_neg100_br(i32 %x, ptr %p) {
; CHECK-LABEL: test_cmp_neg100_br:
; CHECK:      ext 8190
; CHECK-NEXT: cmp %r12, 28
; CHECK-NOT:  ld.w %r{{[0-9]+}}, 28
entry:
  %c = icmp eq i32 %x, -100
  br i1 %c, label %a, label %b
a:
  store i32 11, ptr %p
  ret void
b:
  store i32 22, ptr %p
  ret void
}

; cmp with full 32-bit immediate requires 2 ext instructions
define void @test_cmp_big_br(i32 %x, ptr %p) {
; CHECK-LABEL: test_cmp_big_br:
; CHECK:      ext {{[0-9]+}}
; CHECK-NEXT: ext {{[0-9]+}}
; CHECK-NEXT: cmp %r12, {{-?[0-9]+}}
entry:
  %c = icmp eq i32 %x, 123456789
  br i1 %c, label %a, label %b
a:
  store i32 11, ptr %p
  ret void
b:
  store i32 22, ptr %p
  ret void
}
