; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=s1c33 -O2 < %s | FileCheck %s

; Verify that large-immediate ALU operations use ext+ri form (not ext+ld.w+rr).

; and with 16-bit mask — constant optimization (ld.uh) is expected
define i32 @test_and_16bit(i32 %a) {
; CHECK-LABEL: test_and_16bit:
; CHECK-NOT: ld.w {{%r[0-9]+}}, 65535
entry:
  %r = and i32 %a, 65535
  ret i32 %r
}

; or with large constant: ext + or (2 instrs, not 3)
define i32 @test_or_large(i32 %a) {
; CHECK-LABEL: test_or_large:
; CHECK:      ext 1020
; CHECK-NEXT: or %r10, 0
; CHECK-NOT:  ld.w
entry:
  %r = or i32 %a, 65280
  ret i32 %r
}

; xor with 0xFF: ext + xor
define i32 @test_xor_255(i32 %a) {
; CHECK-LABEL: test_xor_255:
; CHECK:      ext 3
; CHECK-NEXT: xor %r10, -1
; CHECK-NOT:  ld.w {{%r[0-9]+}}, 255
entry:
  %r = xor i32 %a, 255
  ret i32 %r
}

; sub with constant > 63: ext + sub
define i32 @test_sub_100(i32 %a) {
; CHECK-LABEL: test_sub_100:
; CHECK:      ext 1
; CHECK-NEXT: sub %r10, 36
; CHECK-NOT:  add
entry:
  %r = sub i32 %a, 100
  ret i32 %r
}

; sub with constant in 0..63: direct sub_ri (no ext)
define i32 @test_sub_small(i32 %a) {
; CHECK-LABEL: test_sub_small:
; CHECK:      sub %r10, 10
; CHECK-NOT:  ext
entry:
  %r = sub i32 %a, 10
  ret i32 %r
}

; Decrement idiom: (add x, -1) → sub x, 1
define i32 @test_decrement(i32 %a) {
; CHECK-LABEL: test_decrement:
; CHECK:      sub %r10, 1
; CHECK-NOT:  ld.w
entry:
  %r = add i32 %a, -1
  ret i32 %r
}

; Decrement by 63: (add x, -63) → sub x, 63
define i32 @test_decrement_63(i32 %a) {
; CHECK-LABEL: test_decrement_63:
; CHECK:      sub %r10, 63
entry:
  %r = add i32 %a, -63
  ret i32 %r
}

; (add x, -100): should become sub x, 100
define i32 @test_add_neg100(i32 %a) {
; CHECK-LABEL: test_add_neg100:
; CHECK:      ext 1
; CHECK-NEXT: sub %r10, 36
; CHECK-NOT:  add %r
entry:
  %r = add i32 %a, -100
  ret i32 %r
}
