; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=s1c33 -O2 < %s | FileCheck %s

; Test that analyzeBranch/reverseBranchCondition eliminates redundant
; unconditional jumps by inverting the condition and falling through.

; Diamond pattern: cmp + jrlt true / jp false → cmp + jrge false (fallthrough to true)
define i32 @test_slt(i32 %a, i32 %b) {
; CHECK-LABEL: test_slt:
; CHECK:       cmp %r12, %r13
; CHECK-NEXT:  jrge .LBB0_2
; CHECK-NOT:   jp
; CHECK:       ld.w %r10, 1
; CHECK:     .LBB0_2:
; CHECK-NEXT:  ret.d
; CHECK-NEXT:  ld.w %r10, 0
entry:
  %cmp = icmp slt i32 %a, %b
  br i1 %cmp, label %then, label %else
then:
  ret i32 1
else:
  ret i32 0
}

; Test unsigned comparison inversion: jrult → jruge
define i32 @test_ult(i32 %a, i32 %b) {
; CHECK-LABEL: test_ult:
; CHECK:       cmp %r12, %r13
; CHECK:       jruge
; CHECK-NOT:   jp
entry:
  %cmp = icmp ult i32 %a, %b
  br i1 %cmp, label %then, label %else
then:
  ret i32 10
else:
  ret i32 20
}

; Test eq inversion: jreq → jrne
define i32 @test_eq(i32 %a, i32 %b) {
; CHECK-LABEL: test_eq:
; CHECK:       cmp %r12, %r13
; CHECK:       jrne
; CHECK-NOT:   jp
entry:
  %cmp = icmp eq i32 %a, %b
  br i1 %cmp, label %then, label %else
then:
  ret i32 1
else:
  ret i32 0
}

; Test gt inversion: jrgt → jrle
define i32 @test_sgt(i32 %a, i32 %b) {
; CHECK-LABEL: test_sgt:
; CHECK:       cmp %r12, %r13
; CHECK:       jrle
; CHECK-NOT:   jp
entry:
  %cmp = icmp sgt i32 %a, %b
  br i1 %cmp, label %then, label %else
then:
  ret i32 1
else:
  ret i32 0
}
